name: Build application for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true --no-restore -o AzureKeyvaultExplorer\bin\Debug\net8.0-windows

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: Azure-Keyvault-Explorer
        path: AzureKeyvaultExplorer\bin\Debug\net8.0-windows

    # - name: Show where we are
    #   run: |
    #       Get-Location
    #       Get-ChildItem -Recurse
