name: Build application for Windows

on:
  push:
    tags:
      - 'v*.*.*'  
  
jobs:
  build:
    strategy:
      matrix:
        project: ['AzureKeyvaultExplorer', 'AzureKeyvaultCLI']
        runtime: ['linux-x64', 'win-x64']
        exclude:
          - project: 'AzureKeyvaultExplorer'
            runtime: 'linux-x64'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore ${{ matrix.project }}/${{ matrix.project }}.csproj
        --runtime ${{ matrix.runtime }}

    - name: Build
      run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj
        --runtime ${{ matrix.runtime }}
        --configuration Release
        --no-restore

    - name: Publish
      run: dotnet publish ${{ matrix.project }}/${{ matrix.project }}.csproj
        --runtime ${{ matrix.runtime }}
        --configuration Release
        --self-contained false
        --no-restore
        --no-build
        --property:PublishSingleFile=true

    - name: List files
      run: Get-ChildItem -Recurse AzureKeyvaultExplorer\bin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: AzureKeyvaultExplorer/bin/Release/net8.0-windows/win-x64/publish/*.exe
