name: Build application for Windows

on:
  push:
    tags:
      - 'v*.*.*'  
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Build
      run: dotnet build 
        --configuration Release
        --no-restore

    - name: Publish
      run: dotnet publish
        --configuration Release
        --self-contained false
        --no-restore
        --no-build
        --property:PublishSingleFile=true

    - name: List files
      run: Get-ChildItem -Recurse AzureKeyvaultExplorer\bin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: AzureKeyvaultExplorer/bin/Release/net8.0-windows/win-x64/publish/*.exe
