name: .NET Core Desktop

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Name: AzureKeyvaultExplorer.sln
      Test_Project_Path: AzureKeyvaultExplorer\AzureKeyvaultExplorer.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Upload artifact directory
      uses: actions/upload-artifact@v4
      with:
        name: artifact-directory
        path: AzureKeyvaultExplorer\bin\Release\net8.0-windows
